#!/bin/bash

# How to?
#
# ./jekyll serve
#

JEKYLL_VERSION=3.8.6
docker run --network=host --rm --volume="$PWD/docs:/srv/jekyll" -e JEKYLL_UID=1001 -e JEKYLL_GID=1001 -it jekyll/jekyll:$JEKYLL_VERSION jekyll $@ --trace
